### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by JamiKettunen** [mer-hybris/dummy_netd#5]
As per https://github.com/mer-hybris/dummy_netd/blob/e4f1800/dummy_netd.c#L1-L31 the source code is licensed under a [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html), yet the repository root is missing a `LICENSE` file, which is required to be distributed along with installed binaries.

**Comment by mlehtima** [comment]
Fix in https://github.com/mer-hybris/dummy_netd/pull/6

**Comment by mlehtima** [comment]
The PR with the fix has now been merged, closing this.
